coecor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^imoveis/', include('imoveis.urls')),
    url(r'^files/', include('db_file_storage.urls')),
    url(r'^.*$', RedirectView.as_view(pattern_name='imoveis:index'))
]

imoveis/urls.py
from django.conf.urls import url

from . import views
app_name = 'imoveis'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<build_id>[0-9]+)/picture$', views.picture, name='picture'),
    url(r'^(?P<pk>[0-9]+)/', views.BuildDetail.as_view(), name='detail'),
    url(r'search', views.search, name='search'),
    url('create_dump', views.create_dump, name='create_dump'),
    url('upload_dump', views.upload_dump, name='upload_dump'),
    url('add_picture', views.add_picture, name='add_picture'),
    url('add_observation', views.add_observation, name='add_observation'),
    url('add_owner', views.add_owner, name='add_owner'),
    url('add_phonenumber', views.add_phonenumber, name='add_phonenumber'),
]

imoveis/models.py
from django.db import models
from django.conf import settings
from django.core.validators import RegexValidator
from djmoney.models.fields import MoneyField

# Create your models here.

class Feature(models.Model):
    description = models.CharField(max_length=200, verbose_name = 'descrição')
    def __str__(self):
        return self.description
    class Meta:
        verbose_name = 'Atributo'
        verbose_name_plural = 'Atributos'
        ordering = ["description"]

class Owner(models.Model):
    name = models.CharField(max_length=200, verbose_name = 'nome')
    email = models.EmailField(max_length=254, blank=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Proprietário'
        verbose_name_plural = 'Proprietários'

class PhoneNumber(models.Model):
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    note = models.CharField(max_length=200, blank=True, null=True,
                            verbose_name = 'nota')
    country_validator = RegexValidator(
        regex = r'^\+[\d\-\.]{1,6}$',
        message = "Um código de país pode ou não começar com um sinal de" +
                  "mais(+) e deve conter até 6 valores. Um valor pode ser um" +
                  "dígito(0-9), um ponto(.) ou um hífen(-)."
    )
    country =  models.CharField(max_length=6, validators=[country_validator],
                                blank=True, default='+55',
                                verbose_name='país')

    state_validator = RegexValidator(
        regex = r'\d{2,3}$',
        message = "Um código de região deve conter até 3 dígitos(0-9)."
    )
    state =  models.CharField(max_length=3,validators=[state_validator],
                              default = '011', verbose_name='estado')

    number_validator = RegexValidator(
        regex = r'\d{8,9}$',
        message = "Um número de telefone deve conter de 8 a 9 dígitos(0-9)."
    )
    number = models.CharField(max_length=9, validators=[number_validator],
                              verbose_name='número')

    def __str__(self):
        if self.country and self.state:
            return "+{} {} {}".format(self.country, self.state, self.number)
        elif self.state:
            return "{} {}".format(self.state, self.number)
        else:
            return str(self.number)

    class Meta:
        verbose_name = 'Telefone'
        verbose_name_plural = 'Telefones'

class PictureFile(models.Model):
    bytes = models.TextField()
    filename = models.CharField(max_length=255)
    mimetype = models.CharField(max_length=50)

class Picture(models.Model):
    title = models.CharField(max_length=200, verbose_name='título')
    picture_file = models.ImageField(
        upload_to='imoveis.PictureFile/bytes/filename/mimetype',
        blank = True,
        null = True)
    def __str__(self):
        return self.title[:20]

    class Meta:
        verbose_name = 'Imagem'
        verbose_name_plural = 'Imagens'

class District(models.Model):
    name = models.CharField(max_length=500, verbose_name='nome')

    def __str__(self):
        return self.name[:10]

    class Meta:
        verbose_name = 'Bairro'
        verbose_name_plural = 'Bairros'
        ordering = ["name"]

class Build(models.Model):
    pub_date = models.DateTimeField('data de cadastro')
    project = models.CharField(max_length=200, blank=True,
                               verbose_name='empreendimento')
    address = models.CharField(max_length=200, blank=True,
                               verbose_name='endereço')
    district =  models.ManyToManyField(District, blank=True,
                                       verbose_name='Bairro')
    SELLING_CHOICES = ((True, 'à venda'), (False, 'vendido'))
    availability = models.BooleanField(choices=SELLING_CHOICES, default=True,
                                       verbose_name='disponibilidade')
    age = models.PositiveIntegerField(default=0, verbose_name='idade')
    building_type = models.CharField(max_length=200, blank=True,
                                     verbose_name='tipo')
    unit = models.PositiveIntegerField(default=0, verbose_name='unidade')
    tower = models.CharField(max_length=200, blank=True, verbose_name='torre')
    FACE_CHOICES = (('N','Norte'), ('S', 'Sul'), ('L', 'Leste'),
                    ('O', 'Oeste'), ('-', 'Não informada'))
    face = models.CharField(max_length=1, choices=FACE_CHOICES, default='-')
    EMPTY_CHOICES = ((True, 'Sim'), (False, 'Não'))
    empty =  models.BooleanField(choices=EMPTY_CHOICES, default=True,
                                 verbose_name='vago')
    selling_price = MoneyField(max_digits=15, verbose_name='valor de venda',
                               default_currency='BRL', decimal_places=2)
    iptu = MoneyField(max_digits=8, decimal_places=2, default_currency='BRL')
    condominium_fee = MoneyField(max_digits=8, decimal_places=2,
                                 default_currency='BRL',
                                 verbose_name='taxa de condomínio')
    square_meters = models.PositiveIntegerField(default=0,
                                                verbose_name='metragem')
    units_per_floor = models.PositiveIntegerField(
        default=0,
        blank=True,
        verbose_name='unidades/andar'
    )
    janitor_name = models.CharField(max_length=200, blank=True,
                                    verbose_name='zelador')
    parking_slots = models.PositiveIntegerField(
        default=0,
        verbose_name='vagas na garagem'
    )
    bedrooms = models.PositiveIntegerField(default=0, verbose_name='quartos')
    bathrooms = models.PositiveIntegerField(default=0,
                                            verbose_name='banheiros')
    suites = models.PositiveIntegerField(default=0, verbose_name='suites')
    features = models.ManyToManyField(Feature, blank=True,
                                      verbose_name='Atributos')
    owners = models.ManyToManyField(Owner, blank=True,
                                    verbose_name='Proprietários')
    pictures = models.ManyToManyField(Picture, blank=True,
                                      verbose_name='Figuras')
    class Meta:
        verbose_name = 'Imóvel'
        verbose_name_plural = 'Imóveis'
        ordering = ["address"]

    def __str__(self):
        return self.address

class Observation(models.Model):
    build = models.ForeignKey(Build, on_delete=models.CASCADE)
    description = models.CharField(max_length = 500, verbose_name='descrição')

    def __str__(self):
        return self.description[:10]

    class Meta:
        verbose_name = 'Observação'
        verbose_name_plural = 'Observações'

imoveis/forms.py
from django import forms
from .models import Picture, Observation, Owner, PhoneNumber

class UploadPictureForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ['title', 'picture_file']

class ObservationForm(forms.ModelForm):
    class Meta:
        model = Observation
        fields = ['build', 'description']

class OwnerForm(forms.ModelForm):
    class Meta:
        model = Owner
        fields = ['name', 'email']

class PhoneNumberForm(forms.ModelForm):
    class Meta:
        model = PhoneNumber
        fields = ['owner', 'country', 'state', 'number']

imoveis/forms/admin.py
from django import forms

from ..models import Build, Observation
from ..widgets.widgets import BootstrapedCheckboxSelectMultiple

class ObservationAdminForm(forms.ModelForm):
    class Meta:
        model = Observation
        fields = ['description']
        widgets = {
            'description': forms.Textarea
        }


class BuildForm(forms.ModelForm):
    class Meta:
        model = Build
        exclude = []
        widgets = {
                'features': BootstrapedCheckboxSelectMultiple(),
                'owners': BootstrapedCheckboxSelectMultiple()
        }

imoveis/forms/forms.py
from django import forms
from ..models import Picture, Observation, Owner, PhoneNumber

class UploadPictureForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ['title', 'picture_file']

class ObservationForm(forms.ModelForm):
    class Meta:
        model = Observation
        fields = ['build', 'description']

class OwnerForm(forms.ModelForm):
    class Meta:
        model = Owner
        fields = ['name', 'email']

class PhoneNumberForm(forms.ModelForm):
    class Meta:
        model = PhoneNumber
        fields = ['owner', 'country', 'state', 'number']

imoveis/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Build
from .forms.forms import UploadPictureForm, ObservationForm, OwnerForm, \
                   PhoneNumberForm
from .dbdump.dump import make_dump, load_dump

# Create your views here.

def index(request):
    context = {
    }
    return render(request, 'imoveis/index.html', context);

@login_required
def detail(request, build_id):
    build = get_object_or_404(Build, pk=build_id)
    context = {
        'build': build,
    }
    return render(request, 'imoveis/detail.html', context);

@login_required
def add_observation(request):
    return add_form_mixin(request, ObservationForm, 'imoveis/picture.html');

@login_required
def add_picture(request):
    return add_form_mixin(request, UploadPictureForm, 'imoveis/picture.html');

@login_required
def add_owner(request):
    return add_form_mixin(request, OwnerForm, 'imoveis/owner.html');

@login_required
def add_phonenumber(request):
    return add_form_mixin(request, PhoneNumberForm, 'imoveis/phonenumber.html');

@login_required
def create_dump(request):
    filename = make_dump()
    resp =  HttpResponse("Dump {} created!".format(filename))
    with open(filename, 'rb') as tmp:
        resp = HttpResponse(tmp, content_type='application/zip')
        resp['Content-Disposition'] = 'attachment; filename={}'.format(
            filename)
    return resp

@login_required
def upload_dump(request):
    if request.method == 'POST':
        filename = request.POST['filename']
        load_dump(filename)
        return HttpResponse("Done!")
    context = {}
    return render(request, 'imoveis/upload_dump.html', context);

@login_required
def picture(request, build_id):
    return HttpResponse("picture of {}".format(build_id))

@login_required
def add_form_mixin(request, form_class, template):
    if request.method == 'POST':
        form = form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/imoveis')
    else:
        form = form_class()
        context = {
            'form': form,
        }
    return render(request, template, context)

@login_required
def search(request):
    if request.method == 'POST':
        query = request.POST['query']
        build_list = Build.objects.filter(address__icontains=query)
    else:
        query=''
        build_list = Build.objects.order_by('pub_date')[:5]
    context = {
        'build_list': build_list,
        'query': query,
    }
    return render(request, 'imoveis/search.html', context);

class BuildList(LoginRequiredMixin, ListView):
    model = Build
    paginate_by = 10
    template_name = 'imoveis/index.html'
    context_object_name = 'build_list'

class BuildDetail(LoginRequiredMixin, DetailView):
    model = Build
    template_name = 'imoveis/detail.html'
    context_object_name = 'build'

imoveis/templates/imoveis/base.html
<html>
  <head>
  {% load static %}

  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

  {% load bootstrap4 %}
	{# Load CSS and JavaScript #}
	{% bootstrap_css %}
	{% bootstrap_javascript %}

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'coecor/style.css' %}"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Berkshire+Swash"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Indie+Flower"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Lilita+One"
      rel="stylesheet"
    />
  </head>
  <body class="my-theme-l5">
    <div class="jumbotron pgh my-theme">
      <h1><a href="/">Coecor Corretora</a></h1>
    </div>
    <div class="container">
      {% block content %}
			{% endblock %}
			{% block pagination %}
			{% if is_paginated %}
			<div class="d-flex flex-row justify-content-center">
        <nav aria-label='Paginação'>
          <ul class='pagination'>
            {% if page_obj.has_previous %}
            <li class='page-item'>
              <a class='page-link'
                 href="{{ request.path }}?page=" +
                      "{{ page_obj.previous_page_number }}">
            {% else %}
            <li class='page-item disabled'>
              <a class='page-link'
                 href="#">
            {% endif %}
                anterior
              </a>
            </li>
            <li class='page-item disabled'>
              <span class="page-link">
                Página {{ page_obj.number }}
                de {{ page_obj.paginator.num_pages }}.
              </span>
            </li>
            {% if page_obj.has_next %}
            <li class='page-item'>
              <a class='page-link'
                href="{{ request.path }}?page={{ page_obj.next_page_number }}">
            {% else %}
            <li class='page-item disabled'>
              <a class='page-link'
                 href="#">
            {% endif %}
                próxima
              </a>
            </li>
          </ul>
      </nav>
    </div>
    {% endif %}
    {% endblock %}
    </div>
    <nav class="navbar navbar-expand-sm bg-secondary navbar-dark fixed-bottom">
      {% if request.user.username %}
      <a class="navbar-brand" href="{% url 'admin:logout' %}">
        Desconectar ({{ request.user.username }})
      </a>
      {% else %}
      <a class="navbar-brand" href="{% url 'imoveis:index' %}">Coecor</a>
      {% endif %}
      <ul class='navbar-nav'>
        <li class='nav-item'>
          <a class='nav-link' href="{% url 'admin:index' %}">
            Admin
          </a>
        </li>
        <li class='nav-item'>
          <a class='nav-link' href="{% url 'imoveis:create_dump' %}">
            Criar Backup
          </a>
        </li>
        <li class='nav-item'>
          <a class='nav-link' href="{% url 'imoveis:search' %}">
            Procurar Imovel
          </a>
        </li>
      </ul>

    </nav>
  </body>
</html>

imoveis/templates/imoveis/detail.html
{% extends 'imoveis/base.html' %}

{% block content %}
  <div class='row pb-2'>
    <h2> {{ build.address }} </h2>
  </div>
  <div class='row pb-2'>
    <div class="col-md-1">
    </div>
    <div class="col-md-10">
      <ul class="list-group">
        <li class="list-group-item my-theme-l4">
          Adicionade em: {{ build.pub_date }}
        </li>
        <li class="list-group-item my-theme-l4">
          Projeto: {{ build.project }}
        </li>
        {% if build.district %}
        <li class="list-group-item my-theme-l4">
          Bairro: {{ build.district }}
        </li>
        {% endif %}
        {% if build.tower %}
        <li class="list-group-item my-theme-l4">
          Torre: {{ build.tower }}
        </li>
        {% endif %}
        <li class="list-group-item my-theme-l4"> Status:
          {% if build.availability %}
          À venda
          {% else %}
          Vendido
          {% endif %}
        </li>
      </ul>
    </div>
    <div class="col-md-1">
    </div>
  </div>

  {% if build.pictures.all %}
  <div class='row pb-2'>
    <div class='col-md-3'>
    </div>
    <div id="picture-show" class="carousel slide col-md-6" data-ride="carousel">
      <ol class="carousel-indicators">
        {% for picture in build.pictures.all %}
        {% if forloop.counter0 == 0 %}
        <li data-target="#picture-show" data-slide-to="0" class="active"></li>
        {% else %}
        <li data-target="#picture-show" data-slide-to="{{ forloop.counter0 }}" class="active"></li>
        {% endif %}
        {% endfor %}
      </ol>
      <div class="carousel-inner">
        {% for picture in build.pictures.all %}
        {% if forloop.counter == 1 %}
        <div class="carousel-item active">
        {% else %}
        <div class="carousel-item">
        {% endif %}
          <img style="width: 100%; height: 300px;" src="{{ picture.picture_file.url }}">
        </div>
        {% endfor %}
      </div>
      <a class="carousel-control-prev" href="#picture-show" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only" style="color: #000000;">Previous</span>
      </a>
      <a class="carousel-control-next" href="#picture-show" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <div class='col-md-3'>
    </div>
  </div>
  {% endif %}

  <div class='row pb-2'>
    <div class="col-md-1">
    </div>
    <div id='accordion' role='tablist' aria-multiselect-table='true' class='col-md-10'>
      <div class='card'>
        <div class='card-header' role='tab' id='details'>
          <h5 class='mb-0'>
            <a data-toggle='collapse' data-parent='#accordion'
                href='#details_body' aria-expanded='false'>
              Detalhes
            </a>
          </h5>
        </div>
        <div id='details_body' class='collapse hide' role='tabpanel'
             aria-labelledby= 'detail'>
          <div class='card-block'>
            <ul class="list-group">
              <li class="list-group-item my-theme-l4">
                Idade: {{ build.age }}
              </li>
              <li class="list-group-item my-theme-l4">
                Tipo: {{ build.building_type }}
              </li>
              <li class="list-group-item my-theme-l4">
                Unidade: {{ build.unity }}
              </li>
              <li class="list-group-item my-theme-l4">
                Face:
                {% if build.face == 'N' %} Norte
                {% elif build.face == 'S' %} Sul
                {% elif build.face == 'L' %} Leste
                {% elif build.face == 'O' %} Oeste
                {% endif %}
              </li>
              <li class="list-group-item my-theme-l4">
                Vazio:
                {% if build.empty %} Sim
                {% else %} Não
                {% endif %}
              </li>
              <li class="list-group-item my-theme-l4">
                Valor de venda: {{ build.selling_price }}
              </li>
              <li class="list-group-item my-theme-l4">
                Condomínio: {{ build.condominium_fee }}
              </li>
              <li class="list-group-item my-theme-l4">
                IPTU: {{ build.iptu }}
              </li>
              <li class="list-group-item my-theme-l4">
                Tamanho: {{ build.square_meters }} m<sup>2</sup>
              </li>
              <li class="list-group-item my-theme-l4">
                Unidades por andar: {{ build.units_per_floor }}
              </li>
              <li class="list-group-item my-theme-l4">
                Zelador: {{ build.janitor_name }}
              </li>
              <li class="list-group-item my-theme-l4">
                Vagas na garagem: {{ build.parking_slots }}
              </li>
              <li class="list-group-item my-theme-l4">
                Quartos: {{ build.bedrooms }}
              </li>
              <li class="list-group-item my-theme-l4">
                Banheiros: {{ build.bathrooms }}
              </li>
              <li class="list-group-item my-theme-l4">
                Suites: {{ build.suites }}
              </li>
              {% for owner in build.owners.all %}
              <li class="list-group-item my-theme-l4">
                <li class="list-group-item my-theme-l4">
                  Proprietário: {{ owner }}
                </li>
                <li class="list-group-item my-theme-l4">
                  Contato: {{ owner.email }}
                </li>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class='card-header' role='tab' id='observations'>
          <h5 class='mb-0'>
            <a data-toggle='collapse' data-parent='#accordion'
                href='#observations_body' aria-expanded='false'>
              Observações
            </a>
          </h5>
        </div>
        <div id='observations_body' class='collapse hide' role='tabpanel'
             aria-labelledby= 'observations'>
          <div class='card-block'>
            <ul class="list-group">
              {% for observation in build.observation_set.all %}
              <li class="list-group-item my-theme-l4">
                {{ observation.description }}
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-1">
    </div>
  </div>
  {% endblock %}

imoveis/templates/imoveis/forms.html
{% extends 'imoveis/base.html' %}

{% load static %}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}


{% block content %}
  <div class="row">
    <div class="col-md-8">
      {% block form_title %}
      {% endblock %}

      {% if error_message %}
        <p><strong> {{ error_message }} </strong></p>
      {% endif %}

      <form
         method="post"
         enctype="multipart/form-data"
         class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button type="submit" class="btn btn-primary"> Enviar </button>
        {% endbuttons %}
      </form>
    </div>
  </div>

{% endblock %}

imoveis/templates/imoveis/index.html
{% extends 'imoveis/base.html' %}
{% block content %}
  {% if request.user.username %}
  Bem-vindo {{ request.user.username }}
  {% else %}
  <a href="{% url 'admin:login' %}?next={% url 'imoveis:index'%}">
    Você ainda precisa se identificar
  </a>
  {% endif %}
{% endblock %}

imoveis/templates/imoveis/observation.html
{% extends 'imoveis/forms.html' %}

{% block form_title %}
  <h2> Adicionar observação </h2>
{% endblock %}

imoveis/templates/imoveis/owner.html
{% extends 'imoveis/forms.html' %}

{% block form_title %}
  <h2> Adicionar proprietário </h2>
{% endblock %}

imoveis/templates/imoveis/phonenumber.html
{% extends 'imoveis/forms.html' %}

{% block form_title %}
  <h2> Adicionar telefone </h2>
{% endblock %}

imoveis/templates/imoveis/picture.html
{% extends 'imoveis/forms.html' %}

{% block form_title %}
  <h2> Adicionar imagem </h2>
{% endblock %}

imoveis/templates/imoveis/search.html
{% extends 'imoveis/base.html' %}
{% block content %}
  <div class='row pb-2'>
    <div class='col-md-9'>
      <form method='post' class='form'>
        {% csrf_token %}
        <input type='text' name='query' placeholder='pesquisar' value={{ query}}>
      </form>
    </div>
    <div class='col-md-3'>
    </div>
  </div>
  {% if query %}
  <div class='row pb-2'>
    <div class='col-md-9'>
    <h4> Resultados da busca por:</h4>
    '{{ query }}'
    </div>
    <div class='col-md-3'>
    </div>
  </div>
  {% endif %}
  <div class='row pb-2'>
    <div class='col-md-12'>
      {% if build_list %}
        <ul class="list-group">
        {% for build in build_list %}
        <li class="list-group-item">
          <a href="{% url 'imoveis:detail' build.id %}">{{ build.address }}</a>
        </li>
        {% endfor %}
        </ul>
      {% else %}
        <p> Nenhum imóvel encontrado </p>
      {% endif %}
    </div>
  </div>
{% endblock %}

imoveis/templates/imoveis/upload_dump.html
{% extends 'imoveis/base.html' %}
{% block content %}
  <div class='row pb-2'>
    <div class='col-md-9'>
      <form method='post' class='form'>
        {% csrf_token %}
        <input type='text' name='filename' placeholder='filename'>
      </form>
    </div>
    <div class='col-md-3'>
    </div>
  </div>
{% endblock %}